#!/usr/bin/env bash
#
# NAME:
#   ds18b20 - show all DS18B20 sensors' address and value
#
# SYNOPSIS:
#   ds18b20
#
# DESCRIPTION:
# - Script displays addresses of all DS18B20 sensors connected to the system, one address per line.
# - Script displays current values of all DS18B20 sensors connected to the system.
#
# LICENSE:
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
ls -d1 /sys/bus/w1/devices/28-*
cat    /sys/bus/w1/devices/28-*/w1_slave
